version: '3.9'

services:
  spring-boot-app:
    build: ../
    ports:
      - "8080:8080"
    volumes:
      - spring-boot-app:/app
    depends_on:
      - postgres


  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
volumes:
    postgres_data:
    spring-boot-app:
